### PR TITLE
Work done 💪

### PR DESCRIPTION
**Pull request by rodrigograca31**
## Description

In this challenge, create a web page that presents a styled list of Star Wars characters. Being able to render out data to a web page is a large part of what JavaScript developers do, this challenge assesses your ability to achieve such a task.

## Self-Study/Essay Questions

Demonstrate your understanding of this Sprint's concepts by answering the following free-form questions. Edit this document to include your answers after each question. Make sure to leave a blank line above and below your answer so it is clear and easy to read by your project manager.

- [x] What is React JS and what problems does it try and solve? Support your answer with concepts introduced in class and from your personal research on the web.
> React is a lib to build web UIs using web tech like HTML, JS, CSS.
> It solves the problem of creating a web UI fast and easy
- [x] What does it mean to _think_ in react?
> It means think modularly, UI, state, data flow
- [x] Describe state.
> State is state. Meaning its the state of something, in react its the state of the variables that its olding, their values is their state.
- [x] Describe props.
> Is a set of variables that you pass down to your components
- [x] What are side effects, and how do you sync effects in a React component to state or prop changes?
> Side efects are thing that should not happend every time React renders the UI, 
> You can mate it track a particular state like this:
```
useEffect(() => {
  }, STATE_TO_TRACK);
```

## Project Set Up

Follow these steps to set up and work on your project:

- [x] Create a forked copy of this project.
- [x] Add TL as collaborator on Github.
- [x] Clone your OWN version of Repo. **(Not Lambda's by mistake!)**
- [x] Create a new Branch locally: `git checkout -b <firstName-lastName>`.
- [x] Change directories into `./starwars` (`cd starwars`) and run `yarn install` or `npm install` to retrieve all needed dependencies.
- [x] Once you have installed the _node_modules_, run `yarn start` or `npm start` to get your server up and running.
- [x] With the server up and running, open Chrome and head over to `localhost:3000` and view your beautiful app. Maybe it's not _that_ pretty... _yet_, your goal is to ensure this project becomes a thing of beauty.
Follow these steps for completing your project.
- [x] Implement the project on this Branch, **committing progress & changes often.**
- [x] Push commits: `git push origin <firstName-lastName>`.

Follow these steps for completing your project:

- [x] Submit a Pull-Request to merge <firstName-lastName> Branch into master (student's  Repo).
- [x] Add your Project Manager as a Reviewer on the Pull-request.
- [x] PM then will count the HW as done by merging the branch back into master.

## Minimum Viable Product

Your finished project must include all of the following requirements:

- [x] Fetch a list of Star Wars characters from the [Star Wars API (or SWAPI)](https://swapi.co/) and render them to the screen. 
- [x] Follow the documentation to learn how to fetch a list of "people". However, don't spend _too_ long on this. Here is a link for you to follow if you've looked around the docs for about 15 minutes or so and haven't found where to go - [Secret Link to Awesomeness 🤫](https://swapi.co/documentation#people).
- [x] Set the data you fetch to state.
- [x] Map over the list and render a component for each character on the page.
- [x] You must display at least one element for each star wars character in the data set.
- [x] The elements must be styled with either Reactstrap or styled-components - don't rely on browser default styles.

#### Required best practices:

- [x] Consistent naming. Examples: variables, functions, Components, and file/folder organization.
- [x] Consistent spacing. Examples: line breaks, around arguments and before/after functions.
- [x] Consistent quotation usage.
- [x] Spell-check.
- [x] Schedule time to review, refine and reassess your work.

It is better to submit a challenge that meets [MVP](https://en.wikipedia.org/wiki/Minimum_viable_product) than one that attempts too much and fails.

## Stretch Problems
- [x] Next week we will be looking at React forms. Look a head and try to create a search form that will filter through the data displayed from your characters. 

- [x] Build a pagination system that will allow you to load the next page of data.
  - `console.log()` the data coming back from the server.
  - Notice that there are `next` and `previous` fields that give you a URL.
  - You can build a function that will get characters called `getCharacters` that you can use dynamically to get the next or previous set of characters. You would need to supply it with the proper fields, and you'll need to set up more state to do this.
  - [x] Add at least one test using a testing tool:
  - [react-testing-library](https://github.com/testing-library/react-testing-library#basic-example)
  - [Cypress](https://docs.cypress.io/guides/overview/why-cypress.html)

### CODE REVIEW

**Review by Becheru888 — APPROVED** [review]
Wow, this looks great Rodrigo,

image

The way you implemented dynamic ID's is really smart now the real problem is whoever wants to search for a character has to know the name of it 😄 

First of all, this is clean and well-structured code, well done!

If you are not familiar with ESlint although I doubt it, please install it! 
You will see some magic happening 😃  

You demonstrate a good understanding of React Components and Component State, Passing Data Via Props, Side Effects and bootstrap.

You are doing a great job here Rodrigo, keep doing it 👍

**Comment by rodrigograca31** [comment]
I've been using prettier and literally got it working correctly during the sprint challenge :joy: 
even said that to Idir:
image

but why you say to install eslint?

**Comment by Becheru888** [comment]
because of ESlint is kinda Grammarly for JS

**Comment by rodrigograca31** [comment]
prettier seems to work better for me..... just tried eslint and asks to install on the project and etc.... :angry:

**Pull request merged**
